local:
  key: application-local

common :
  common :
    key : applicationCommon
  key : oommon

logging:
  file:
    path: /Users/subinjang/DEV/workspace/upload/logs/wjpjt/backend
    name : wjpjt-backend-api
